apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: handle-notebook-workflow-
  namespace: argo
  labels:
    workflows.argoproj.io/workflow-template: handle-notebook-workflow
    submit-from-ui: 'true'
spec:
  arguments:
    parameters:
      - name: scheduled_notebook_id
        value: 66123b940263ba0de6361df5
  workflowTemplateRef:
    name: handle-notebook-workflow
