apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: handle-notebook-workflow
spec:
  entrypoint: handle
  arguments:
    parameters:
    - name: scheduled_notebook_id
      value: 65e61f7dd92706945575a3de

  templates:
  - name: handle
    steps:
    - - name: first
        template: initialize-notebook
        arguments:
          parameters:
          - name: notebook_service_url
            value: http://notebookservice.default.svc.cluster.local:12700
          - name: file_service_url
            value: http://fileservice.default.svc.cluster.local:12600
          - name: scheduled_notebook_id
            value: "{{workflow.parameters.scheduled_notebook_id}}"
    - - name: second
        template: generate-parameter
        arguments:
          parameters:
          - name: generator_service_url
            value: http://generatorservice.default.svc.cluster.local:12800
          artifacts:
          - name: input_parameters_to_generate_file_path
            from: "{{steps.first.outputs.artifacts.input_parameters_to_generate_output_file_path}}"
    - - name: third
        template: run-notebook
        arguments:
          artifacts:
          - name: notebook_input_path
            from: "{{steps.first.outputs.artifacts.notebook_output_file_path}}"
          - name: input_parameters_file_path
            from: "{{steps.first.outputs.artifacts.input_parameters_output_file_path}}"
          - name: output_parameters_file_path
            from: "{{steps.first.outputs.artifacts.output_parameters_names_output_file_path}}"
          - name: input_parameters_to_generate_output
            from: "{{steps.second.outputs.artifacts.input_parameters_to_generate_output_file_path}}"
    - - name: forth
        template: finish-notebook
        arguments:
          parameters:
          - name: notebook_service_url
            value: http://notebookservice.default.svc.cluster.local:12700
          - name: scheduled_notebook_id
            value: "{{workflow.parameters.scheduled_notebook_id}}"
          artifacts:
          - name: output_parameters_file_path
            from: "{{steps.third.outputs.artifacts.output_parameters_output_file_path}}"

  - name: initialize-notebook
    inputs:
      parameters:
      - name: notebook_service_url
      - name: file_service_url
      - name: scheduled_notebook_id
    outputs:
      artifacts:
      - name: notebook_output_file_path
        path: /notebook_output.txt
      - name: input_parameters_output_file_path
        path: /input_parameters_output.txt
      - name: input_parameters_to_generate_output_file_path
        path: /input_parameters_to_generate_output.json
      - name: output_parameters_names_output_file_path
        path: /output_parameters_names.txt
    container:
      # run cowsay with that message input parameter as args
      image: catalibugnar/initialize_notebook@sha256:70802c1b95c1fa64ff89a6a30ee9bb7e47dd51ed85e76b7602e4c58c2000cccb
      command: [python3, /app/init_notebook.py]
      args:
      - --notebook_service_url
      - "{{inputs.parameters.notebook_service_url}}"
      - --file_service_url
      - "{{inputs.parameters.file_service_url}}"
      - --scheduled_notebook_id
      - "{{inputs.parameters.scheduled_notebook_id}}"
      - --notebook_output_file_path
      - "/notebook_output.txt"
      - --input_parameters_output_file_path
      - "/input_parameters_output.txt"
      - --input_parameters_to_generate_output_file_path
      - "/input_parameters_to_generate_output.json"
      - --output_parameters_names_output_file_path
      - "/output_parameters_names.txt"

  - name: generate-parameter
    inputs:
      parameters:
      - name: generator_service_url
      artifacts:
        - name: input_parameters_to_generate_file_path
          path: /input_parameters_to_generate_output.json
    outputs:
      artifacts:
      - name: input_parameters_to_generate_output_file_path
        path: /generated_output_parameters.json
    container:
      # run cowsay with that message input parameter as args
      image: catalibugnar/generate_parameter@sha256:e125bc24bba22391b9eedfd44558724ff6949b9058e8bc8bffac1d5cf3ce3e39
      command: [python3, /app/generate_parameter.py]
      args:
      - --generator_service_url
      - "{{inputs.parameters.generator_service_url}}"
      - --input_parameters_to_generate_file_path
      - "/input_parameters_to_generate_output.json"
      - --input_parameters_to_generate_output_file_path
      - "/generated_output_parameters.json"

  - name: run-notebook
    inputs:
      artifacts:
        - name: notebook_input_path
          path: /notebook_output.txt
        - name: input_parameters_file_path
          path: /input_parameters_output.txt
        - name: input_parameters_to_generate_output
          path: /generated_output_parameters.json
        - name: output_parameters_file_path
          path: /output_parameters_names.txt
    outputs:
      artifacts:
      - name: output_parameters_output_file_path
        path: /output_parameters_output.txt
    container:
      # run cowsay with that message input parameter as args
      image: catalibugnar/run_notebook@sha256:d8169d86083de518190c2fe496268542eda8e34af88537c175f5c7d20c36efdd
      command: [python3, /app/run_notebook.py]
      args:
      - --notebook_input_path
      - "/notebook_output.txt"
      - --input_parameters_file_path
      - "/input_parameters_output.txt"
      - --input_parameters_to_generate_output
      - "/generated_output_parameters.json"
      - --output_parameters_file_path
      - "/output_parameters_names.txt"
      - --output_parameters_output_file_path
      - "/output_parameters_output.txt"

  - name: finish-notebook
    inputs:
      parameters:
      - name: notebook_service_url
      - name: scheduled_notebook_id
      artifacts:
      - name: output_parameters_file_path
        path: /output_parameters_file_path.txt
    container:
      # run cowsay with that message input parameter as args
      image: catalibugnar/finish_notebook@sha256:1f3ae90fbb2c23f0ec33c260fb0ecdaa4cc2cd2f9e375859b9d23b2a2766955f
      command: [python3, /app/finish_notebook.py]
      args:
      - --notebook_service_url
      - "{{inputs.parameters.notebook_service_url}}"
      - --scheduled_notebook_id
      - "{{inputs.parameters.scheduled_notebook_id}}"
      - --output_parameters_file_path
      - "/output_parameters_file_path.txt"