version: '3.4'

services:
  fileservice.webapi:
    image: ${DOCKER_REGISTRY-}fileservicewebapi
    build:
      context: .
      dockerfile: FileService.WebApi/Dockerfile
    ports:
      - "12600:12600"
    environment:
      FILESERVICE_BINDING_ADRESS: http://*
      FILESERVICE_BINDING_PORT: 12600
      FILESERVICE_MINIO_ENDPOINT: minio:9000
      FILESERVICE_MINIO_ACCESS_KEY: your_username
      FILESERVICE_MINIO_SECRET_KEY: your_pasword
      FILESERVICE_CONNECTION_STRING: mongodb://mongodb:27017/app
      OTEL_URL: http://otel:4317
    depends_on:
      - minio
      - mongodb
      - otel
  
  minio:
    image: docker.io/bitnami/minio:2024.2.26
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: your_username
      MINIO_ROOT_PASSWORD: your_pasword

  mongodb:
    image: bitnami/mongodb:6.0.2
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: app
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 200M

  otel:
    # See https://opentelemetry.io/docs/collector/
    image: otel/opentelemetry-collector-contrib:0.95.0
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - 4317:4317  # gRPC receiver
      - "8889"  # Prometheus exporter metrics
      - "13133" # health_check extension
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro

  prometheus:
    # See https://prometheus.io/docs/prometheus/latest/installation/#using-docker
    image: prom/prometheus:v2.49.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:ro

  jaeger:
    # See https://www.jaegertracing.io/docs/1.38/deployment/#all-in-one
    image: jaegertracing/all-in-one:1.54.0
    ports:
      - "14269"     # Admin port (health check and /metrics)
      - 16686:16686 # Jaeger frontend
      - "4317"      # Trace data receive port (otlp).