version: '3.4'

services:
  userservice.webapi:
    image: ${DOCKER_REGISTRY-}userservicewebapi
    build:
      context: .
      dockerfile: Userservice.WebApi/Dockerfile
    ports:
      - "12500:12500"
    environment:
      USERSERVICE_BINDING_ADRESS: http://*
      USERSERVICE_BINDING_PORT: 12500
      USERSERVICE_CONNECTION_STRING: mongodb://mongodb:27017/app
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: app
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 200M

volumes:
  data-volume:
    name: db-data