apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloack-ingress
spec:
  rules:
    - host: aiworkflow.com
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80